name: Build Site

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  Trigger-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Call Gatsby Cloud Webhook
        id: rebuild
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{secrets.GATSBY_WEBHOOK}}
          method: 'POST'
      env:
      GATSBY_WEBHOOK: ${{secrets.GATSBY_WEBHOOK}}
