name: Build every 5 minutes
on:
  schedule:
    - cron: '*/5 * * * *'
  jobs:
    Do-Things:
      runs-on: ubuntu-latest
      steps:
        - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
